### ISSUE TITLE
求助，无法配网

### ISSUE THREAD

**Issue by 337047705** [IoTDevice/phicomm_tc1_a2#1]
求助，刷了您的固件之后再次ttl刷机就无输出了，两台都是这样的情况，刷机都已经百分之百，且无错误，现在无法重新刷。开机并没有散出无线网，所以也无法配网，开机后按住开机键也不散热点，如果长按会出现指示灯闪一下之后灭掉，然后再按按键就没有反应了，只能拔电，请求指导一下

**Comment by IoTServ** [comment]
QQ群（251227638）里有一些人刷这个固件，你可以过来跟他们交流一下，入群答案：斐讯

**Comment by 337047705** [comment]
加了群问了没人理，所以才求助，现在我ttl可以在界面输入文字，但是没有输出，且短接两个点直接断电，，不知道该怎么办了

**Comment by IoTServ** [comment]
你这可能是是没有刷成功，按照操作重新刷
