### ISSUE TITLE
按一下空格键吗？还是按几下都可以？我的一直出现乱码（我是连按了好几下），不出现bootloader。

### ISSUE THREAD

**Issue by fobin-hit** [IoTDevice/phicomm_tc1_a2#2]
按一下空格键吗？我是连按几下空格键，一直出现乱码，出现不了bootloader。

**Comment by fobin-hit** [comment]
> 按一下空格键吗？我是连按几下空格键，一直出现乱码，出现不了bootloader。

**Comment by IoTServ** [comment]
按好几下也没事，最主要是按的速度要够快

**Comment by fobin-hit** [comment]
> 按好几下也没事，最主要是按的速度要够快

一直出现乱码，乱码看上去以汉字为主。绝对是1秒内按的空格键。有什么其他注意事项吗？1.已经按教程方式测试，确认usb转ttl可用2.确认接线正确3.打开com3端口能连接（左上角显示绿色√）。

**Comment by IoTServ** [comment]
我是刚通电，然后在串口那里按一下连接(先把右键调出菜单，鼠标放重连选项上，上电后点一下再空格)，然后再空格，你有么有在群251227638里，里面有详细一些的文档

**Comment by fobin-hit** [comment]
在群里问过，但没有解决问题。打开SecureCRTPortable，连接com3，tc1 a2连接电脑usb，按住tc1 a2按键，短接测试点，按电脑空格。我是这样操作，但一直乱码。您看下流程有问题吗？您qq多少，我加你？

**Comment by IoTServ** [comment]
你QQ多少，我加你

**Comment by fobin-hit** [comment]
qq：809317360，您加下
